# Generated by Django 5.2.8 on 2025-12-17 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_user_roles_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('phone_primary', models.CharField(max_length=50, unique=True)),
                ('phone_secondary', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('referral_type', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudiologistCaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField()),
                ('family_history', models.TextField()),
                ('noise_exposure', models.TextField()),
                ('previous_ha_experience', models.TextField()),
                ('red_flags', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to='clinical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(max_length=255)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('present_complaint', models.CharField(blank=True, max_length=255, null=True)),
                ('test_requested', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinical.patient')),
                ('seen_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, help_text='Auto-generated bill number', max_length=100, null=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount (auto-calculated from bill items)', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount applied', max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final amount after discount', max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(help_text='One bill per visit', on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='clinical.patientvisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Test name (e.g., PTA, OAE, BERA/ASSR)', max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short code for the test', max_length=50, null=True, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of the test', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, help_text='If null, applies to all clinics', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('technology_level', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_size', models.CharField(blank=True, max_length=255, null=True)),
                ('ear_fitted', models.CharField(blank=True, max_length=50, null=True)),
                ('dome_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gain_settings', models.TextField(blank=True, null=True)),
                ('srt_before', models.CharField(blank=True, max_length=255, null=True)),
                ('sds_before', models.CharField(blank=True, max_length=255, null=True)),
                ('ucl_before', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_response', models.CharField(blank=True, max_length=255, null=True)),
                ('counselling_notes', models.TextField()),
                ('discount_offered', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost associated with the trial', max_digits=10, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinic')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Test', 'Test'), ('Trial', 'Trial')], help_text='Type of item: Test or Trial', max_length=10)),
                ('description', models.CharField(help_text='Description of the item', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of this item', max_digits=10)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity (usually 1 for tests/trials)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='clinical.bill')),
                ('test_type', models.ForeignKey(blank=True, help_text="If item_type is 'Test', link to TestType", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='clinical.testtype')),
                ('trial', models.ForeignKey(blank=True, help_text="If item_type is 'Trial', link to Trial", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='clinical.trial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitTestPerformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pta', models.BooleanField(default=False)),
                ('immittance', models.BooleanField(default=False)),
                ('oae', models.BooleanField(default=False)),
                ('bera_assr', models.BooleanField(default=False)),
                ('srt', models.BooleanField(default=False)),
                ('sds', models.BooleanField(default=False)),
                ('ucl', models.BooleanField(default=False)),
                ('free_field', models.BooleanField(default=False)),
                ('other_test', models.CharField(blank=True, max_length=255, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='TestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.visittestperformed')),
            ],
        ),
    ]
