# Generated by Django 5.2.8 on 2025-12-17 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_roles_user_role'),
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='model',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='technology_level',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='visit',
        ),
        migrations.AddField(
            model_name='trial',
            name='trial_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='trial_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='item_type',
            field=models.CharField(choices=[('Test', 'Test'), ('Trial', 'Trial'), ('Service', 'Service')], help_text='Type of item: Test / Trial / Service', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_primary',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Battery', 'Battery'), ('Dome', 'Dome'), ('Receiver', 'Receiver'), ('Mold', 'Mold'), ('Tube', 'Tube'), ('Hearing Aid', 'Hearing Aid'), ('Trial Stock', 'Trial Stock'), ('Speech Material', 'Speech Material')], max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('model_type', models.CharField(max_length=100)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('use_in_trial', models.BooleanField(default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['category', 'brand', 'model_type'],
            },
        ),
        migrations.AddField(
            model_name='trial',
            name='device_inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.inventoryitem'),
        ),
        migrations.CreateModel(
            name='InventorySerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Trial', 'Trial'), ('Sold', 'Sold'), ('Service', 'Service'), ('Lost', 'Lost')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('ear_fitted', models.CharField(max_length=20)),
                ('purchase_date', models.DateField()),
                ('warranty_start', models.DateField()),
                ('warranty_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='clinical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('Consumable', 'Consumable'), ('Device', 'Device')], max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.inventoryitem')),
                ('inventory_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.inventoryserial')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='clinical.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='clinical.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('TGA', 'TGA'), ('Machine Check', 'Machine Check'), ('Cleaning', 'Cleaning'), ('Dome Change', 'Dome Change'), ('Filter Change', 'Filter Change'), ('Battery Change', 'Battery Change'), ('Receiver Change', 'Receiver Change'), ('Tube Change', 'Tube Change'), ('Quick Tuning', 'Quick Tuning'), ('Repair', 'Repair')], max_length=50)),
                ('complaint', models.TextField()),
                ('action_taken', models.TextField()),
                ('warranty_applicable', models.BooleanField(default=False)),
                ('charges_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rtc_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.patientdevice')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='clinical.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePartUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinical.inventoryitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='clinical.servicevisit')),
            ],
        ),
        migrations.AddField(
            model_name='billitem',
            name='service_visit',
            field=models.ForeignKey(blank=True, help_text="If item_type is 'Service', link to ServiceVisit", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='clinical.servicevisit'),
        ),
    ]
