# Generated by Django 5.2.8 on 2025-11-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiologistCaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField()),
                ('family_history', models.TextField()),
                ('noise_exposure', models.TextField()),
                ('previous_ha_experience', models.TextField()),
                ('red_flags', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='TestsPerformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pta', models.BooleanField(default=False)),
                ('immittance', models.BooleanField(default=False)),
                ('oae', models.BooleanField(default=False)),
                ('bera_assr', models.BooleanField(default=False)),
                ('srt', models.BooleanField(default=False)),
                ('sds', models.BooleanField(default=False)),
                ('ucl', models.BooleanField(default=False)),
                ('free_field', models.BooleanField(default=False)),
                ('other_test', models.CharField(blank=True, max_length=255, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='TestsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pta', models.BooleanField(default=False)),
                ('tympanometry', models.BooleanField(default=False)),
                ('srt', models.BooleanField(default=False)),
                ('sds', models.BooleanField(default=False)),
                ('ucl', models.BooleanField(default=False)),
                ('free_field', models.BooleanField(default=False)),
                ('bera_assr', models.BooleanField(default=False)),
                ('oae', models.BooleanField(default=False)),
                ('special_test', models.BooleanField(default=False)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='TestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('technology_level', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('srt_before', models.CharField(blank=True, max_length=255, null=True)),
                ('sds_before', models.CharField(blank=True, max_length=255, null=True)),
                ('ucl_before', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_response', models.CharField(max_length=255)),
                ('counselling_notes', models.TextField()),
                ('discount_offered', models.FloatField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinic')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patientvisit')),
            ],
        ),
    ]
