# Generated by Django 5.2.8 on 2025-12-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_remove_trial_brand_remove_trial_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='assignn_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.patient'),
        ),
    ]
