# Generated by Django 5.2.8 on 2025-12-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_trial_assignn_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='clinic',
        ),
    ]
