# Generated by Django 5.2.8 on 2025-12-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_remove_inventoryitem_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='has_serial_number',
            field=models.BooleanField(default=False),
        ),
    ]
