# Generated by Django 5.2.8 on 2025-12-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_inventoryitem_has_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='has_serial_number',
        ),
    ]
