# Generated by Django 5.2.8 on 2025-12-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_roles_user_role'),
        ('clinical', '0006_remove_inventoryitem_has_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevisit',
            name='device',
            field=models.ForeignKey(help_text='The purchased item being serviced.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.patientpurchase'),
        ),
        migrations.RemoveField(
            model_name='patientpurchase',
            name='purchase_type',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10, help_text='Alert when stock falls to this level'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_type',
            field=models.CharField(choices=[('Serialized', 'Serialized'), ('Non-Serialized', 'Non-Serialized')], default='Non-Serialized', max_length=20),
        ),
        migrations.AddField(
            model_name='patientpurchase',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinic'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='device_serial',
            field=models.ForeignKey(blank=True, help_text='The specific serialized item being serviced.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.inventoryserial'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='PatientDevice',
        ),
    ]
