# Generated by Django 5.2.8 on 2025-12-19 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_alter_servicevisit_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='assignn_patient',
            new_name='assigned_patient',
        ),
        migrations.AddField(
            model_name='trial',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical.patientvisit'),
        ),
    ]
