# Generated by Django 5.2.8 on 2025-12-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_rename_assignn_patient_trial_assigned_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryserial',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='clinical.inventoryitem'),
        ),
    ]
